/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

// Using const assertion to get a readonly tuple of string literals
export const occasionOptions = [
  'occasion_mariage_invite',
  'occasion_mariage_ceremonie',
  'occasion_mariage_soiree',
  'occasion_cocktail',
  'occasion_diner_romantique',
  'occasion_travail_rdv',
  'occasion_reunion_commerciale',
  'occasion_presentation',
  'occasion_entretien',
  'occasion_boite',
  'occasion_lounge',
  'occasion_restaurant',
  'occasion_dejeuner',
  'occasion_cinema',
  'occasion_concert',
  'occasion_festival',
  'occasion_voyage',
  'occasion_balneaire',
  'occasion_randonnee',
  'occasion_sport',
  'occasion_shopping',
  'occasion_famille',
  'occasion_bapteme',
  'occasion_gala',
  'occasion_vernissage',
  'occasion_reception',
  'occasion_garden',
  'occasion_nouvel_an',
  'occasion_noel',
  'occasion_funerailles',
  'occasion_defile',
  'occasion_rooftop',
  'occasion_brunch',
  'occasion_deguisement',
  'occasion_shooting',
  'occasion_afterwork',
  'occasion_shoppingvip',
  'occasion_caritatif',
  'occasion_bal_masque',
  'occasion_rave',
  'occasion_beachparty',
  'occasion_picnic',
  'occasion_karaoke',
  'occasion_lancement',
  'occasion_coloc',
  'occasion_speeddating',
  'occasion_jazzclub',
  'occasion_yacht',
  'occasion_theatre',
  'occasion_apero',
  'occasion_tennis',
  'occasion_running',
  'occasion_cyclisme',
  'occasion_yoga',
  'occasion_boxe',
  'occasion_natation',
  'occasion_danse',
  'occasion_ski',
  'occasion_surf',
  'occasion_football',
  'occasion_basketball',
  'occasion_swim_onepiece',
  'occasion_swim_twopiece',
  'occasion_swim_tankini',
  'occasion_swim_beach',
  'occasion_swim_pool',
  'occasion_swim_ocean',
  'occasion_swim_lake',
] as const;

// Deriving the type from the const array
export type OccasionKey = typeof occasionOptions[number];